[package]
name = "gobject-example"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]

[dependencies]
bitflags = "0.9"
libc = "0.2"
glib-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = { git = "https://github.com/gtk-rs/sys" }
glib = { git = "https://github.com/gtk-rs/glib" }

[lib]
crate-type = ["cdylib"]

[features]
default-features = []
bindings = []
